In [1]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
result=np.split(arr,3)
print(result)

ValueError: array split does not result in an equal division

In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
result=np.hsplit(arr,3)
print(result)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [10]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=np.split(arr,3)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [11]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
result=np.dsplit(arr,2)
print(result)

[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [12]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)

(array([1, 4], dtype=int64),)


In [13]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x1=np.where(arr%2==0)
print(x1)

(array([1, 2, 4, 5], dtype=int64),)


In [14]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x2=np.searchsorted(arr, 3, side='left')
print(x2)

1


In [15]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x2=np.searchsorted(arr, 8, side='right')
print(x2)

6
