In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [2]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [3]:
import numpy as np
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))


[[4 7 9]
 [1 4 9]]


In [15]:
arr=np.array([31,78,68,88])
x=[False, True, True, False]
newarr=arr[x]
print(x)
print(newarr)

[False, True, True, False]
[78 68]


In [16]:
arr=np.array([31,78,68,88])
filter_arr=arr>70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[78 88]


In [6]:
import numpy as np
arr1=[20,40,50,70,10]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]


In [7]:
import numpy as np
arr1=[20,40,50,70,10]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a.dot(b))
sclr=3
print("\n Scalar Value :\n",sclr)
print("\n Result :\n", a*sclr)

1150

 Scalar Value :
 3

 Result :
 [ 60 120 150 210  30]


In [9]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [14]:
def my_function(x,y):
    if x>y:
        return x-y
    else:
        return x+y
    arr1=[10,7,2]
    arr2=[6,5,3]
    vect_func=np.vectorize(my_func)
    print("Array1 :",arr1)
    print("Array2 :",arr2)
    print("Result :",vect_func(arr1,arr2))
