In [3]:
import numpy as np
a=np.array([[10,20,30],[50,80,70]])
print(a)
print("Array Created: ", a)

[[10 20 30]
 [50 80 70]]
Array Created:  [[10 20 30]
 [50 80 70]]


In [4]:
import numpy as np
b=np.array([10,15,20,25,30])
print('One Dimensional Array: ',b)

One Dimensional Array:  [10 15 20 25 30]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros: \n",c)


 Array with all zeros: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random values: \n",d)


 Random values: 
 [[0.05263474 0.0955177  0.12447859]
 [0.74060231 0.91698516 0.94066361]
 [0.59621076 0.07178752 0.81241859]]


In [7]:
import numpy as np
e=np.arange(0,40,5)
print("\n A sequence of array with step 5: \n",e)


 A sequence of array with step 5: 
 [ 0  5 10 15 20 25 30 35]


In [8]:
import numpy as np
f=np.full((3,4),(7))
print(f)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [10]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
klj=kl.reshape(4,3)
print("\n Original Array: \n",kl)
print("\n Reshaped Array: \n",klj)


 Original Array: 
 [[22 12  5 19]
 [22  7 20 23]
 [ 6  8  5 16]]

 Reshaped Array: 
 [[22 12  5]
 [19 22  7]
 [20 23  6]
 [ 8  5 16]]


In [11]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
fl=kl.flatten()
print("\n Original Array: \n",kl)
print("\n Flattened Array: \n",fl)


 Original Array: 
 [[22 12  5 19]
 [22  7 20 23]
 [ 6  8  5 16]]

 Flattened Array: 
 [22 12  5 19 22  7 20 23  6  8  5 16]


In [12]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
print("\n No. of dimensions: ",kl.ndim)


 No. of dimensions:  2


In [14]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
print("\n Shape of the Array: \n",kl.shape)


 Shape of the Array: 
 (3, 4)


In [15]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
print("\n Type of the Element in the Array: \n",kl.dtype)


 Type of the Element in the Array: 
 int32


In [16]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
newtype=kl.astype('f')
print("\n Converted Array: \n",newtype)
print("\n Converted Array Type: \n",newtype.dtype)


 Converted Array: 
 [[22. 12.  5. 19.]
 [22.  7. 20. 23.]
 [ 6.  8.  5. 16.]]

 Converted Array Type: 
 float32


In [17]:
import numpy as np
kl=np.array([[22,12,5,19],[22,7,20,23],[6,8,5,16]])
size=len(kl)
print("\n Size of Array: \n",size)


 Size of Array: 
 3
